/**
 * Re-exports vikeApiRouterMiddleware from the virtual module generated by the Vite plugin.
 *
 * The virtual module imports routes and handlers statically so Vite can resolve
 * them at bundle time — avoiding runtime `virtual:` URL imports that break in
 * Node.js SSR worker threads (ERR_UNSUPPORTED_ESM_URL_SCHEME).
 */
export { vikeApiRouterMiddleware } from 'virtual:vike-api-router/middleware'
