import type { ApiContext, MiddlewareFn, RouteHandler } from '../types.js'
import { isDefineRoute } from '../define.js'

/**
 * A route manifest entry as generated by the virtual module.
 */
export interface RouteManifestEntry {
  method: string
  path: string
  handler: RouteHandler
  middlewares: MiddlewareFn[]
}

/**
 * Normalize a route handler's return value to a Response.
 */
function normalizeResponse(result: Awaited<ReturnType<RouteHandler>>): Response {
  if (result instanceof Response) return result
  if (result == null) return new Response(null, { status: 204 })
  return new Response(JSON.stringify(result), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  })
}

/**
 * Extract path params from a matched URL against a route pattern.
 * Handles :param segments and * wildcards.
 */
function extractParams(routePath: string, urlPath: string): Record<string, string> {
  const routeSegments = routePath.split('/').filter(Boolean)
  const urlSegments = urlPath.split('/').filter(Boolean)
  const params: Record<string, string> = {}

  for (let i = 0; i < routeSegments.length; i++) {
    const rs = routeSegments[i]
    if (rs === '*') {
      params['*'] = urlSegments.slice(i).join('/')
      break
    } else if (rs.startsWith(':')) {
      params[rs.slice(1)] = urlSegments[i] ?? ''
    }
  }

  return params
}

/**
 * Check if a URL path matches a route pattern.
 */
function matchRoute(routePath: string, urlPath: string): boolean {
  const routeSegments = routePath.split('/').filter(Boolean)
  const urlSegments = urlPath.split('/').filter(Boolean)

  if (routeSegments[routeSegments.length - 1] === '*') {
    const prefixSegments = routeSegments.slice(0, -1)
    if (urlSegments.length < prefixSegments.length) return false
    return prefixSegments.every((seg, i) => seg.startsWith(':') || seg === urlSegments[i])
  }

  if (routeSegments.length !== urlSegments.length) return false

  return routeSegments.every((seg, i) => seg.startsWith(':') || seg === urlSegments[i])
}

/**
 * Build a request handler for a single route that chains middlewares → route handler.
 *
 * The resulting function takes a Request and returns a Response using Web standard APIs.
 */
export function buildRouteHandler(entry: RouteManifestEntry): (req: Request) => Promise<Response> {
  return async (req: Request): Promise<Response> => {
    const url = new URL(req.url, 'http://localhost')
    const params = extractParams(entry.path, url.pathname)

    const ctx: ApiContext = {
      params,
      req,
      method: req.method,
    }

    // Unwrap defineRoute result if present, merging its middlewares after route middlewares
    const routeHandler = isDefineRoute(entry.handler) ? entry.handler.handler : entry.handler
    const allMiddlewares = isDefineRoute(entry.handler)
      ? [...entry.middlewares, ...entry.handler.middlewares]
      : entry.middlewares

    // Build middleware chain around the route handler
    const handle = async (): Promise<Response> => {
      const result = await routeHandler(ctx)
      return normalizeResponse(result)
    }

    // Chain middlewares in reverse order so the first middleware runs first
    let chain = handle
    for (let i = allMiddlewares.length - 1; i >= 0; i--) {
      const mw = allMiddlewares[i]
      const next = chain
      chain = () => mw(req, next)
    }

    return chain()
  }
}

/**
 * A simple universal router that matches requests to route entries.
 *
 * Used by the middleware to dispatch incoming requests.
 */
export function createRouter(routes: RouteManifestEntry[]) {
  const handlers = routes.map(entry => ({
    entry,
    handle: buildRouteHandler(entry),
  }))

  return {
    async dispatch(req: Request): Promise<Response | undefined> {
      const url = new URL(req.url, 'http://localhost')
      const method = (req.method ?? 'GET').toUpperCase()

      for (const { entry, handle } of handlers) {
        if (!matchRoute(entry.path, url.pathname)) continue
        if (entry.method !== 'ALL' && entry.method !== method) continue
        return handle(req)
      }

      return undefined
    },
  }
}
