/**
 * Client-side proxy for RPC handlers defined in server/handlers/.
 *
 * Import handler functions from here to call them from client code.
 * They will transparently make HTTP calls to the server.
 *
 * @example
 * ```ts
 * import { handlers } from 'vike-api-router/client'
 * const user = await handlers.userHandler.getUser('123')
 * ```
 */

// The actual proxy implementation is generated by the Vite plugin into a virtual module.
// In dev/build, this module is replaced by the virtual:vike-api-router/handlers-client module.
export { handlers } from 'virtual:vike-api-router/handlers-client'
