/**
 * Client-side proxy for RPC handlers defined in server/handlers/index.ts.
 *
 * Import the default export and access handler methods via property access.
 * Each method call transparently makes an HTTP POST to the server.
 *
 * @example
 * ```ts
 * import handlers from 'vike-api-router/handlers'
 * const data = await handlers.oladoctor.get('/api/doctors')
 * ```
 */

// The actual proxy implementation is generated by the Vite plugin into a virtual module.
// In dev/build, this module is replaced by the virtual:vike-api-router/handlers-client module.
export { default } from 'virtual:vike-api-router/handlers-client'
