/**
 * Client-side proxy for RPC handlers defined in server/handlers/.
 *
 * Import named handler objects from here to call server functions from client code.
 * Each function call transparently makes an HTTP POST to the server.
 *
 * @example
 * ```ts
 * import { userHandler } from 'vike-api-router/handlers'
 * const user = await userHandler.getUser('123')
 * ```
 */

// The actual proxy implementation is generated by the Vite plugin into a virtual module.
// In dev/build, this module is replaced by the virtual:vike-api-router/handlers-client module.
export * from 'virtual:vike-api-router/handlers-client'
