/**
 * Client-side proxy for RPC handlers defined in server/handlers/index.ts.
 *
 * Import named handlers from here to call server functions from client code.
 * Each method call transparently makes an HTTP POST to the server.
 *
 * @example
 * ```ts
 * import { oladoctor } from 'vike-api-router/handlers'
 * const data = await oladoctor.get('/api/doctors')
 * ```
 */

// The actual proxy implementation is generated by the Vite plugin into a virtual module.
// In dev/build, this module is replaced by the virtual:vike-api-router/handlers-client module.
export * from 'virtual:vike-api-router/handlers-client'
